version: '3.8'

services:
  # Using pre-built version (recommended)
  clice:
    build:
      context: .
      dockerfile: Dockerfile.prebuilt
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: [ "--mode=pipe" ]
    environment:
      - CLICE_LOG_LEVEL=info

  # Using source-built version
  clice-build:
    build: .
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: [ "--mode=pipe" ]
    environment:
      - CLICE_LOG_LEVEL=info

  # Development container with shell access (pre-built)
  clice-dev:
    build:
      context: .
      dockerfile: Dockerfile.prebuilt
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    environment:
      - CLICE_LOG_LEVEL=debug
